import type { Lesson } from "@/lib/types";

export const fallbackLesson: Lesson = {
  id: "fallback-fractions-story-v1",
  mode: "story",
  title: "The Pizza Tournament: Fraction Showdown",
  subject: "Math",
  focus: "Adding fractions with the same denominator",
  childName: "Buddy",
  intro: "Hey Buddy! Imagine you are running a pizza tournament where teams compete by eating the most slices. Let us figure out the math behind who wins!",
  reflection: "You discovered the golden rule of fraction addition: when pizzas are cut the same way, just count up the slices! Next time you split anything into equal parts, you will know exactly how to add them up like a tournament champion.",
  scenes: [
    {
      index: 0,
      narrative: "Picture a pizza cut into 8 perfectly equal slices. When we write a fraction, it is just a way of saying how many slices we took out of the total slices. The bottom number is called the denominator, and it tells us how many equal pieces the whole thing was divided into.",
      question: {
        id: "q1",
        sceneIndex: 0,
        prompt: "If a pizza has 8 slices and I write 3/8, what does the 8 on the bottom tell us?",
        hint: "Think about what happened to the pizza before anyone ate it. How was it prepared?",
        deeperHint: "The pizza was CUT into 8 equal pieces. That bottom number counts total pieces.",
        answer: "how many equal pieces the pizza was cut into",
        accept: ["8 slices", "total slices", "total pieces", "how many pieces", "the whole pizza", "denominator", "equal parts"],
      },
    },
    {
      index: 1,
      narrative: "Round 1 of the tournament! You grab 2 slices out of 8, which we write as 2/8. Your teammate grabs 3 slices from the same pizza, written as 3/8. Together, your team ate some fraction of the pizza. Let us figure it out!",
      question: null,
    },
    {
      index: 2,
      narrative: "Here is the key insight: the pizza did not change! It is still 8 slices total. Only the eaten slices add up. So 2/8 plus 3/8 equals 5/8. The rule is: same denominator means keep the bottom number, and just add the top numbers!",
      question: {
        id: "q2",
        sceneIndex: 2,
        prompt: "Your team ate 5/8. If one more teammate eats 2 slices from the same pizza, what fraction did your team eat in total?",
        hint: "Same pizza, same bottom number. What is 5 plus 2?",
        deeperHint: "Keep the denominator (8). Add the numerators: 5 + 2 = 7. So it is 7/8!",
        answer: "7/8",
        accept: ["7/8", "seven eighths", "7 over 8", "seven out of eight"],
      },
    },
    {
      index: 3,
      narrative: "Watch out! Here is where people mess up. Some people add BOTH numbers and get 5/16. But think about it: you did not cut the pizza into 16 slices! The pizza is still 8 slices. Only the eaten part changes. Adding denominators would be like pretending you have a totally different pizza.",
      question: {
        id: "q3",
        sceneIndex: 3,
        prompt: "Why can't we add the denominators when adding fractions with the same bottom number?",
        hint: "Did anyone cut the pizza into more slices? Or is it the same pizza?",
        deeperHint: "The pizza is still divided into the same number of slices. Adding denominators would mean pretending we have a 16-slice pizza, which we do not!",
        answer: "because the total number of slices didn't change",
        accept: ["pizza didn't change", "same pizza", "still 8 slices", "denominator stays same", "whole doesn't change", "not more pieces"],
      },
    },
    {
      index: 4,
      narrative: "Sudden death round! Your team gets one more chance. You eat 2 slices from a fresh 8-slice pizza. Your teammate eats 3 more. Then your substitute player eats 1 more. Together that is 2/8 plus 3/8 plus 1/8, which equals 6/8. It works with 3 fractions too! Same rule, same bottom number.",
      question: {
        id: "q4",
        sceneIndex: 4,
        prompt: "In a 6-slice pizza: you eat 1 slice, your friend eats 2, and your dog sneaks 1. What fraction was eaten? Use the same rule!",
        hint: "The pizza has 6 slices (that is your denominator). Add up everyone's slices on top: 1 + 2 + 1 = ?",
        deeperHint: "Numerator: 1 + 2 + 1 = 4. Denominator stays 6. So the answer is 4/6.",
        answer: "4/6",
        accept: ["4/6", "four sixths", "4 over 6", "four out of six", "4 out of 6"],
      },
    },
  ],
  questions: [
    {
      id: "q1",
      sceneIndex: 0,
      prompt: "If a pizza has 8 slices and I write 3/8, what does the 8 on the bottom tell us?",
      hint: "Think about what happened to the pizza before anyone ate it. How was it prepared?",
      deeperHint: "The pizza was CUT into 8 equal pieces. That bottom number counts total pieces.",
      answer: "how many equal pieces the pizza was cut into",
      accept: ["8 slices", "total slices", "total pieces", "how many pieces", "the whole pizza", "denominator", "equal parts"],
    },
    {
      id: "q2",
      sceneIndex: 2,
      prompt: "Your team ate 5/8. If one more teammate eats 2 slices from the same pizza, what fraction did your team eat in total?",
      hint: "Same pizza, same bottom number. What is 5 plus 2?",
      deeperHint: "Keep the denominator (8). Add the numerators: 5 + 2 = 7. So it is 7/8!",
      answer: "7/8",
      accept: ["7/8", "seven eighths", "7 over 8", "seven out of eight"],
    },
    {
      id: "q3",
      sceneIndex: 3,
      prompt: "Why can't we add the denominators when adding fractions with the same bottom number?",
      hint: "Did anyone cut the pizza into more slices? Or is it the same pizza?",
      deeperHint: "The pizza is still divided into the same number of slices. Adding denominators would mean pretending we have a 16-slice pizza, which we do not!",
      answer: "because the total number of slices didn't change",
      accept: ["pizza didn't change", "same pizza", "still 8 slices", "denominator stays same", "whole doesn't change", "not more pieces"],
    },
    {
      id: "q4",
      sceneIndex: 4,
      prompt: "In a 6-slice pizza: you eat 1 slice, your friend eats 2, and your dog sneaks 1. What fraction was eaten? Use the same rule!",
      hint: "The pizza has 6 slices (that is your denominator). Add up everyone's slices on top: 1 + 2 + 1 = ?",
      deeperHint: "Numerator: 1 + 2 + 1 = 4. Denominator stays 6. So the answer is 4/6.",
      answer: "4/6",
      accept: ["4/6", "four sixths", "4 over 6", "four out of six", "4 out of 6"],
    },
  ],
};
